### ISSUE TITLE
meleu's ToDo list for RAWeb 2.0

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAWeb#101]
I'm diving on HTML/CSS/PHP/Laravel (maybe some JavaScript later) and want to join the development here as soon as the Laravel (`framework`) branch "becomes a reality".

I'm going to use this issue thread to post about what I envisage for RAWeb.

This is going to be a kind of my personal ToDo list. Things I really want to see on the site and will focus my attention to implement (if not implemented by Master @luchaos before me :sweat_smile:). Of course, many of these needs to be discussed before implemented.

Any feedback is apprecieated.

- [ ] solve the [reported bugs](https://github.com/RetroAchievements/RAWeb/issues?q=is%3Aissue+is%3Aopen+label%3Abug).

- [ ] add a powerful notification system, where people can be `@tagged` and receive notifications when tagged. I would like to see this feature for everywhere on the site: forum posts, game's pages, cheevo's pages, tickets, user walls, etc...

- [ ] achievement creators profile page should have a section similar to the "Site Awards" but with the icons of tthe games they worked on.

- [ ] add more info on the notification email, maybe adding the content of the new post (issue #6).

- [ ] add blog-like system to replace the "News". Where the RA staff can communicate with the community in a broader way. The content would be pretty much what we already post on those discord channels under NEWS category plus whatever we think that deserves to be announced.
  - optional: posts with tags (e.g.: aotw, lotw, newset, dev-news, community-news)
  - optional: repost to twitter?
  - optional: comments?

- [ ] add a poll system. A fast google about "laravel poll system" makes me believe that we can have our own poll system. It would be a **really really really** cool feature to make all the community participate on RA decisions (revisions, events, most anticipated sets, whatever we need to decide.).

- [ ] rework the user levels [**note**: luchaos is already working on this]. Currently I think about these ones:
  - unregistered: not confirmed subscription via email.
  - registered: regular user.
  - developer: able to link/unlink games, create leaderboards, edit RPS, manage tickets and upload/demote cheevos to/from the Core.
  - moderator: able to edit others' posts, mottos, and profile picture (avoiding offensive messages/pictures, sharing links for copyrighted material, etc.), also able to move forum topics for another section/category.
  - staff: able to post on the blog (annoucing AotW, LofW, new sets, community events, etc.), set up a poll.
  - admin: able to manually award cheevos, change others' user level, and every action on the user levels listed above.

- [ ] add an audit log (issue #11).

- [ ] developer's feed (issue #162).

- [ ] add a new report type for ticket manager: "Issue with title or description":
    - make it possible to filter tickets by report type.
    - make it possible for admins or the author to edit the title/description on the website.

- [x] ability to [un]subscribe forum topics, game's wall, etc. (issue #5)
- [x] achievement's page: show the number of open tickets (and a link for this list).

- [x] add a way to list all devs, all admins, all cheevos created by a dev, etc.
