### ISSUE TITLE
Documentation: write a setup guide in wiki

### ISSUE THREAD

**Issue by luchaos** [RetroAchievements/RAWeb#22]
- [x] getting started
- [x] add link to README
- [ ] requirements/setup guides
- [ ] project installation/configuration

**Comment by kdecks** [comment]
Many thanks.

**Comment by luchaos** [comment]
readme includes most of it. reopen if more clarification is needed.
